spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: 0
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # create, create-drop, validate, update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: java-e-commerce-edu-case
  spring:
    devtools:
      add-properties: false